### ISSUE TITLE
memoirs-0.1.2 crate has wrong name

### ISSUE THREAD

**Issue by brson** [rust-lang/crates.io-index#1]
The file `me/mo/memoirs` lists versions 0.1.2 of the 'memoirs' crate (lowercase). This crate file is uploaded though as 'Memoirs-0.1.2.crate'.

**Comment by alexcrichton** [comment]
After rust-lang/cargo#1205, https://github.com/rust-lang/crates.io/commit/1c94b84c1f3bdb286c17a3bd33ee7194882f0732, and https://github.com/rust-lang/crates.io/commit/c3f45785e44a10d3664085977ac507ed03763984 are all in place I'll update the index manually to account for this.
