### ISSUE TITLE
failed to download package  from https://crates.io/api/v1/crates/

### ISSUE THREAD

**Issue by eBoyy** [rust-lang/crates.io-index#6]
Actually, I can't download any package from this website: [Crates.io](https://crates.io/api/v1/crates/).

And when I visit this website by my browser, I got an error message from the page:
 >Oops, that route doesn't exist!'. 
 
 
I wonder if it is my network problem(I'm in China) or something wrong with the crates website? 

When I try to use cargo to build or install racer, I got these messages:
>
	zmz:racer eBoy$ cargo build --release --verbose
 		Downloading unicode-xid v0.0.3
	unable to get packages from source
	Caused by:
 		failed to download package `unicode-xid v0.0.3` from https://crates.io/api/v1/crates/	unicode-xid/0.0.3/download
	Caused by:
 	 Timeout was reached    
===
 	 
>
	zmz:racer eBoy$ cargo install --git 'https://github.com/phildawes/racer.git' --verbose
    Updating git repository `https://github.com/phildawes/racer.git`
 	Downloading unicode-xid v0.0.3
	Downloading syntex_syntax v0.24.0
	failed to compile `racer v1.1.0 (https://github.com/phildawes/racer.git#6409afcd)`, 	intermediate artifacts can be found at `/Users/zmz/rust/racer/target-install`
	Caused by:
 		unable to get packages from source
	Caused by:
  		failed to download package `syntex_syntax v0.24.0` from https://crates.io/api/v1/crates/		syntex_syntax/0.24.0/download
	Caused by:
 		SSL connect error

**Comment by alexcrichton** [comment]
Thanks for the report! This was likely an intermittent issue (with timeouts) so it's likely been resolved since then, so closing.
